---
title: "New_figs"
author: "KCB"
date: "4/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

est_fig <- ggplot(df2, aes(x = est_TL, y = est_RB)) + geom_point() +
  geom_polygon(mapping = aes(x=x, y=y), data = df.cipoly, inherit.aes = FALSE,
             alpha = .3) + 
  xlab('TL') + 
  ylab('RB') + 
  geom_line(mapping = aes(x = TL, y = RB), data = df.mean, 
            inherit.aes = FALSE, lwd = 0.5) + 
  geom_pointrange(aes(ymin = lwr_RB, ymax = upr_RB)) + 
  geom_errorbarh(aes(xmin = lwr_TL, xmax = upr_TL)) + 
    geom_line(mapping = aes(x = TL, y = RB), data = df.mean, 
            inherit.aes = FALSE, lwd = 0.5) + 
 # geom_smooth(method = 'lm', fill = 'blue')  +
  ggtitle('Posterior mean RB/TL measurements and mean linear relationship') + 
  theme_few()
```


```{r}
slope_fig <- ggplot(data.frame(m), aes(x = beta.1., y = beta.2.)) + 
  geom_point() + 
  stat_density_2d(col = 'grey60') + 
  xlab(expression(beta[1])) + 
  ylab(expression(beta[2])) + 
  theme_few() + 
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
```


```{r}
ggarrange(est_fig, slope_fig, ncol = 1)
```

